name: Validate OWASP metadata file

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '*.owasp.yaml'

  push:
    paths:
      - '*.owasp.yaml'

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate asd
        uses: asdasd